name: CD - Firebase Hosting
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build site
        run: yarn build:next
      - name: Move site build to functions folder
        run: cp -r .next/ functions/.next
      - name: Install Dependencies
        run: cd functions && yarn install && cd ..
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
